
const cartActionsTypes = {
    ADD_ITEM: 'ADD_ITEM',
    CHANGE_ITEM_COUNT: 'CHANGE_ITEM_COUNT',
    START_CLEAR_ITEM: 'START_CLEAR_ITEM',
    CLEAR_ITEM: 'CLEAR_ITEM', 
    CANCEL_CLEAR_ITEM: 'CANCEL_CLEAR_ITEM',
    APPLY_COUPON: 'APPLY_COUPON',
    CHECKOUT_SUCCESS: 'CHECKOUT_SUCCESS'
}

export default cartActionsTypes