
const STORE_PRODUCTS = [
    {
        id: 1,
        title: "JBL Everest Elite 700 Headphones",
        price: 98,
        discount: 0,
        imageUrl: "https://i.imgur.com/8GVEeRT.png",
        color: "black",
        brand:"jbl",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 2,
        title: "JBL E55 Headphones Wireless",
        price: 110,
        discount: 0,
        imageUrl: "https://i.imgur.com/uWaKRcZ.png",
        color: "blue",
        brand:"jbl",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 3,
        title: "Noise-cancelling JBL Everest Elite 750",
        price: 87,
        discount: 0,
        imageUrl: "https://i.imgur.com/cG8UVTn.png",
        color: "grey",
        brand:"jbl",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 4,
        title: "Jbl Everest Elite 720",
        price: 100,
        discount: 0,
        imageUrl: "https://i.imgur.com/X4HMZW4.png",
        color: "white",
        brand:"jbl",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 5,
        title: "JBL Reflect Contour 2",
        price: 49,
        discount: 0,
        imageUrl: "https://i.imgur.com/RCacu9n.png",
        color: "black",
        brand:"jbl",
        type: "earphones",
        bluetooth: true
    },
    {
        id: 6,
        title: "JBL Bluetooth Stereophonic sound earphones",
        price: 58,
        discount: 0,
        imageUrl: "https://i.imgur.com/O2NZRgP.png",
        color: "blue",
        brand:"jbl",
        type: "earphones",
        bluetooth: true
    },
    {
        id: 7,
        title: "Under Armour Sport JBL earphones",
        price: 60,
        discount: 0,
        imageUrl: "https://i.imgur.com/bTJzpbA.png",
        color: "blue",
        brand:"jbl",
        type: "earphones",
        bluetooth: true
    },
    {
        id: 8,
        title: "JBL T450 Wireless Headphones",
        price: 86,
        discount: 0,
        imageUrl: "https://i.imgur.com/26FqXjO.png",
        color: "black",
        brand:"jbl",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 9,
        title: "Jbl Everest Elite 750",
        price: 90,
        discount: 0,
        imageUrl: "https://i.imgur.com/Uqf44ef.png",
        color: "blue",
        brand:"jbl",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 10,
        title: " Jbl E25 earphones",
        price: 48,
        discount: 0,
        imageUrl: "https://i.imgur.com/g7Zh3Pw.png",
        color: "blue",
        brand:"jbl",
        type: "earphones",
        bluetooth: true
    },
    {
        id: 11,
        title: "JBL T450 Microphone Headphones Sound",
        price: 120,
        discount: 0,
        imageUrl: "https://i.imgur.com/WyPwRue.png",
        color: "white",
        brand:"jbl",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 12,
        title: "Jbl T110 earphones with Phone Connector",
        price: 28,
        discount: 0,
        imageUrl: "https://i.imgur.com/KHiis2K.png",
        color: "black",
        brand:"jbl",
        type: "earphones",
        bluetooth: false
    },
    {
        id: 13,
        title: "Jbl Everest 700 headphones",
        price: 124,
        discount: 0,
        imageUrl: "https://i.imgur.com/JGCECwV.png",
        color: "black",
        brand:"jbl",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 14,
        title: "JBL Reflect Aware Active noise control",
        price: 32,
        discount: 0,
        imageUrl: "https://i.imgur.com/O8jLMXX.png",
        color: "green",
        brand:"jbl",
        type: "earphones",
        bluetooth: false
    },
    {
        id: 15,
        title: "JBL Reflect Response earphones Wireless",
        price: 48,
        discount: 0,
        imageUrl: "https://i.imgur.com/jkPrsPv.png",
        color: "blue",
        brand:"jbl",
        type: "earphones",
        bluetooth: true
    },
    {
        id: 16,
        title: "JBL Microphone earphones",
        price: 30,
        discount: 0,
        imageUrl: "https://i.imgur.com/ZtT6QDx.png",
        color: "red",
        brand:"jbl",
        type: "earphones",
        bluetooth: true
    },
    {
        id: 17,
        title: "JBL E20 with phone connector",
        price: 24,
        discount: 0,
        imageUrl: "https://i.imgur.com/bBCEbFI.png",
        color: "black",
        brand:"jbl",
        type: "earphones",
        bluetooth: false
    },
    {
        id: 18,
        title: "JBL Evereste 750 pro bluetooth",
        price: 98,
        discount: 0,
        imageUrl: "https://i.imgur.com/tbQR7Tf.png",
        color: "black",
        brand:"jbl",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 19,
        title: "Headphones JBL Wireless Audio Sound",
        price: 96,
        discount: 0,
        imageUrl: "https://i.imgur.com/IcEbS9g.png",
        color: "white",
        brand:"jbl",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 20,
        title: "Noise-cancelling headphones JBL E45",
        price: 80,
        discount: 0,
        imageUrl: "https://i.imgur.com/p6o9RdM.png",
        color: "black",
        brand:"jbl",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 21,
        title: "Headphones Microphone Headset JBL E35",
        price: 58,
        discount: 0,
        imageUrl: "https://i.imgur.com/1vEIg6t.png",
        color: "black",
        brand:"jbl",
        type: "headphones",
        bluetooth: false
    },
    {
        id: 22,
        title: "JBL Everest 310 Microphone",
        price: 78,
        discount: 0,
        imageUrl: "https://i.imgur.com/qA4N47o.png",
        color: "black",
        brand:"jbl",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 23,
        title: "JBL earbuds elite 450",
        price: 60,
        discount: 0,
        imageUrl: "https://i.imgur.com/w3KQqfK.png",
        color: "black",
        brand:"jbl",
        type: "earbus",
        bluetooth: true
    },
    {
        id: 24,
        title: "Bluetooth JBL Everest Elite 300",
        price: 76,
        discount: 0,
        imageUrl: "https://i.imgur.com/YBD710B.png",
        color: "blue",
        brand:"jbl",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 25,
        title: "JBL fill 200 earphones",
        price: 24,
        discount: 0,
        imageUrl: "https://i.imgur.com/qJSXEkt.png",
        color: "black",
        brand:"jbl",
        type: "earphones",
        bluetooth: false
    },
    {
        id: 26,
        title: "JBL Reflect Mini earphones Bluetooth",
        price: 58,
        discount: 0,
        imageUrl: "https://i.imgur.com/kYHCDsY.png",
        color: "red",
        brand:"jbl",
        type: "earphones",
        bluetooth: true
    },
    {
        id: 27,
        title: "JBL T450 Headphones Microphone Sound",
        price: 60,
        discount: 0,
        imageUrl: "https://i.imgur.com/NFf4uT8.png",
        color: "white",
        brand:"",
        type: "headphones",
        bluetooth: false
    },
    {
        id: 28,
        title: "JBL E55 Headphones JBL E45 Audio",
        price: 88,
        discount: 0,
        imageUrl: "https://i.imgur.com/4Hgpuml.png",
        color: "pink",
        brand:"jbl",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 29,
        title: "JBL Headphones Harman Kardon Audio",
        price: 57,
        discount: 0,
        imageUrl: "https://i.imgur.com/7ZiQCzD.png",
        color: "blue",
        brand:"jbl",
        type: "headphones",
        bluetooth: false
    },
    {
        id: 30,
        title: "JBL Audio Harman Kardon Harman",
        price: 68,
        discount: 0,
        imageUrl: "https://i.imgur.com/dRc56od.png",
        color: "pink",
        brand:"jbl",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 31,
        title: "JBL T450 Headphones",
        price: 100,
        discount: 0,
        imageUrl: "https://i.imgur.com/j0Z9nAB.png",
        color: "blue",
        brand:"jbl",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 32,
        title: "JBL Synchros E40BT Wireless",
        price: 110,
        discount: 0,
        imageUrl: "https://i.imgur.com/SKgYyiO.png",
        color: "black",
        brand:"jbl",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 33,
        title: "Blue Microphones JBL T450 ",
        price: 120,
        discount: 0,
        imageUrl: "https://i.imgur.com/wSch6ys.png",
        color: "blue",
        brand:"jbl",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 34,
        title: "JBL OR100 Audio earbuds",
        price: 100,
        discount: 0,
        imageUrl: "https://i.imgur.com/NR8U3eQ.png",
        color: "black",
        brand:"jbl",
        type: "earbuds",
        bluetooth: true
    },
    {
        id: 35,
        title: "Beats Electronics Headphones Disc jockey",
        price: 80,
        discount: 0,
        imageUrl: "https://i.imgur.com/D7svVOA.png",
        color: "red",
        brand:"beats",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 36,
        title: "Pink Beats Headphones",
        price: 76,
        discount: 0,
        imageUrl: "https://i.imgur.com/E61nQ6A.png",
        color: "pink",
        brand:"beats",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 37,
        title: "Noise-cancelling Beats Bluetooth headphones",
        price: 78,
        discount: 0,
        imageUrl: "https://i.imgur.com/aTLD3Rc.png",
        color: "blue",
        brand:"beats",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 38,
        title: "Beats Detox Wireless",
        price: 92,
        discount: 0,
        imageUrl: "https://i.imgur.com/ShRBijR.png",
        color: "black",
        brand:"beats",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 39,
        title: "Black cordless headphones",
        price: 92,
        discount: 0,
        imageUrl: "https://i.imgur.com/w4Cmfxv.png",
        color: "black",
        brand:"beats",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 40,
        title: "Beats Solo 2 Electronics Headphones",
        price: 96,
        discount: 0,
        imageUrl: "https://i.imgur.com/v8b8cxC.png",
        color: "black",
        brand:"beats",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 41,
        title: "Beats Studio 2.0 Electronics Headphones",
        price: 100,
        discount: 0,
        imageUrl: "https://i.imgur.com/d6ZbPXo.png",
        color: "blue",
        brand:"beats",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 42,
        title: "Noise-cancelling Beats headphones",
        price: 110,
        discount: 0,
        imageUrl: "https://i.imgur.com/2IFCi30.png",
        color: "gold",
        brand:"beats",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 43,
        title: "Beats lite D23",
        price: 90,
        discount: 0,
        imageUrl: "https://i.imgur.com/OagHw25.png",
        color: "black",
        brand:"beats",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 44,
        title: "Red Beats Bluetooth D26",
        price: 120,
        discount: 0,
        imageUrl: "https://i.imgur.com/wwEs6jl.png",
        color: "red",
        brand:"beats",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 45,
        title: "Grey Beats D40 Pro",
        price: 120,
        discount: 0,
        imageUrl: "https://i.imgur.com/YNgEzAk.png",
        color: "grey",
        brand:"beats",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 46,
        title: "Apple Beats Powerbeats3",
        price: 132,
        discount: 0,
        imageUrl: "https://i.imgur.com/Zrs1s6Y.png",
        color: "white",
        brand:"beats",
        type: "earbuds",
        bluetooth: true
    },
    {
        id: 47,
        title: "Apple Beats Solo³ Headphones",
        price: 89,
        discount: 0,
        imageUrl: "https://i.imgur.com/IZiFtk6.png",
        color: "gold",
        brand:"beats",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 48,
        title: "Beats Solo 2 Headphones Wireless",
        price: 94,
        discount: 0,
        imageUrl: "https://i.imgur.com/bPLhpny.png",
        color: "blue",
        brand:"beats",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 49,
        title: "Blue Beats fill Headphones W2",
        price: 48,
        discount: 0,
        imageUrl: "https://i.imgur.com/Iwht2sJ.png",
        color: "blue",
        brand:"beats",
        type: "headphones",
        bluetooth: false
    },
    {
        id: 50,
        title: "Black Beats fill Headphones W2",
        price: 48,
        discount: 0,
        imageUrl: "https://i.imgur.com/5c7cexo.png",
        color: "black",
        brand:"beats",
        type: "headphones",
        bluetooth: false
    },
    {
        id: 51,
        title: "White Beats fill Headphones W2",
        price: 48,
        discount: 0,
        imageUrl: "https://i.imgur.com/CvRgkO1.png",
        color: "white",
        brand:"beats",
        type: "headphones",
        bluetooth: false
    },
    {
        id: 52,
        title: "Beats BALMAIN earphones Powerbeats3",
        price: 95,
        discount: 0,
        imageUrl: "https://i.imgur.com/O7R2332.png",
        color: "gold",
        brand:"beats",
        type: "earphones",
        bluetooth: true
    },
    {
        id: 53,
        title: "Blue Beats fill A23 headphones Loudspeaker",
        price: 95,
        discount: 0,
        imageUrl: "https://i.imgur.com/WqNUT4w.png",
        color: "blue",
        brand:"beats",
        type: "headphones",
        bluetooth: false
    },
    {
        id: 54,
        title: "Black Beats fill A23 headphones Loudspeaker",
        price: 95,
        discount: 0,
        imageUrl: "https://i.imgur.com/iLpqSJj.png",
        color: "black",
        brand:"beats",
        type: "headphones",
        bluetooth: false
    },
    {
        id: 55,
        title: "Beats Solo3 electronics Headphones",
        price: 110,
        discount: 0,
        imageUrl: "https://i.imgur.com/VCtd63w.png",
        color: "pink",
        brand:"beats",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 56,
        title: "Apple Beats Powerbeats3 Headphones Wireless",
        price: 80,
        discount: 0,
        imageUrl: "https://i.imgur.com/1k60xMV.png",
        color: "grey",
        brand:"beats",
        type: "earphones",
        bluetooth: true
    },
    {
        id: 57,
        title: "Beats Solo 2 Electronics Headphones",
        price: 93,
        discount: 0,
        imageUrl: "https://i.imgur.com/W6vNYsv.png",
        color: "green",
        brand:"beats",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 58,
        title: "Beats W46 last version",
        price: 120,
        discount: 0,
        imageUrl: "https://i.imgur.com/NWxu1kG.png",
        color: "blue",
        brand:"beats",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 59,
        title: "White Beats headphones K25",
        price: 110,
        discount: 0,
        imageUrl: "https://i.imgur.com/jr6vEP6.png",
        color: "white",
        brand:"beats",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 60,
        title: "Beats lite K25",
        price: 130,
        discount: 0,
        imageUrl: "https://i.imgur.com/AADmMHz.png",
        color: "red",
        brand:"beats",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 61,
        title: "Blue Sony cordless headphones",
        price: 130,
        discount: 0,
        imageUrl: "https://i.imgur.com/aeUbVrC.png",
        color: "blue",
        brand:"sony",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 62,
        title: "Black Sony corded headphones",
        price: 58,
        discount: 0,
        imageUrl: "https://i.imgur.com/ec0HKSf.png",
        color: "black",
        brand:"sony",
        type: "headphones",
        bluetooth: false
    },
    {
        id: 63,
        title: "Sony Soundsport Wireless",
        price: 60,
        discount: 0,
        imageUrl: "https://i.imgur.com/TNWv69j.png",
        color: "red",
        brand:"sony",
        type: "headphones",
        bluetooth: false
    },
    {
        id: 64,
        title: "Sony MDR-V6 Headphones Bluetooth Audio Bass",
        price: 80,
        discount: 0,
        imageUrl: "https://i.imgur.com/zJLGb7M.png",
        color: "blue",
        brand:"sony",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 65,
        title: "Sony Xperia S 2018 AirPods",
        price: 98,
        discount: 0,
        imageUrl: "https://i.imgur.com/frzjH6q.png",
        color: "gold",
        brand:"sony",
        type: "earbuds",
        bluetooth: true
    },
    {
        id: 66,
        title: "Sony Xb950 Extra Bass",
        price: 100,
        discount: 0,
        imageUrl: "https://i.imgur.com/5ePvqyy.png",
        color: "black",
        brand:"sony",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 67,
        title: "Sony XB650 EXTRA BASS Wireless",
        price: 80,
        discount: 0,
        imageUrl: "https://i.imgur.com/GGqMXvH.png",
        color: "blue",
        brand:"sony",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 68,
        title: "Sony X3 Earphones",
        price: 72,
        discount: 0,
        imageUrl: "https://i.imgur.com/5j9DxXG.png",
        color: "blue",
        brand:"sony",
        type: "earphones",
        bluetooth: true
    },
    {
        id: 69,
        title: "Noise-cancelling Sony F10 headphones",
        price: 90,
        discount: 0,
        imageUrl: "https://i.imgur.com/SPcauGs.png",
        color: "black",
        brand:"sony",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 70,
        title: "Sony XB550 extra bass Noise-cancelling headphones",
        price: 40,
        discount: 0,
        imageUrl: "https://i.imgur.com/DfsTVgz.png",
        color: "blue",
        brand:"sony",
        type: "headphones",
        bluetooth: false
    },
    {
        id: 71,
        title: "Bose SoundSport earbuds",
        price: 91,
        discount: 0,
        imageUrl: "https://i.imgur.com/bKL5q1T.png",
        color: "black",
        brand:"bose",
        type: "earbuds",
        bluetooth: true
    },
    {
        id: 72,
        title: "Bose SoundLink headphones",
        price: 98,
        discount: 0,
        imageUrl: "https://i.imgur.com/suJ12YK.png",
        color: "white",
        brand:"bose",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 73,
        title: "Bose QuietComfort 35 headphones",
        price: 88,
        discount: 0,
        imageUrl: "https://i.imgur.com/XGcK5D7.png",
        color: "grey",
        brand:"bose",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 74,
        title: "Bose SoundSport Pulse earphones",
        price: 63,
        discount: 0,
        imageUrl: "https://i.imgur.com/Un1VgTA.png",
        color: "black",
        brand:"bose",
        type: "earphones",
        bluetooth: true
    },
    {
        id: 75,
        title: "Headphones Bose Bang & Olufsen",
        price: 56,
        discount: 0,
        imageUrl: "https://i.imgur.com/CMyPltP.png",
        color: "grey",
        brand:"bose",
        type: "headphones",
        bluetooth: false
    },
    {
        id: 76,
        title: "Bose SoundSport Wireless Earbuds",
        price: 60,
        discount: 0,
        imageUrl: "https://i.imgur.com/oRpn8EF.png",
        color: "blue",
        brand:"bose",
        type: "earbuds",
        bluetooth: true
    },
    {
        id: 77,
        title: "AKG Y30 AKG Acoustics Headphones",
        price: 76,
        discount: 0,
        imageUrl: "https://i.imgur.com/lzROKGk.png",
        color: "blue",
        brand:"akg",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 78,
        title: "Blue AKG Y40 Headphones",
        price: 78,
        discount: 0,
        imageUrl: "https://i.imgur.com/C6gYdoE.png",
        color: "blue",
        brand:"akg",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 79,
        title: "AKG Y50 Headphones Wireless",
        price: 80,
        discount: 0,
        imageUrl: "https://i.imgur.com/SFecaG0.png",
        color: "black",
        brand:"akg",
        type: "headphones",
        bluetooth: true
    },
    {
        id: 80,
        title: "AKG fill W60 Headphones",
        price: 51,
        discount: 0,
        imageUrl: "https://i.imgur.com/fIW2v1n.png",
        color: "black",
        brand:"akg",
        type: "headphones",
        bluetooth: false
    },
    {
        id: 81,
        title: "AKG N20 Active noise control",
        price: 42,
        discount: 0,
        imageUrl: "https://i.imgur.com/IZPXNNw.png",
        color: "black",
        brand:"akg",
        type: "earphones",
        bluetooth: false
    }
]